### ISSUE TITLE
google analytics 기능 연결

### ISSUE THREAD

**Issue by jwee01** [effl-lab/effl-lab.github.io#7]
방문자수 체크하면 재미있을 것 같습니다~!

**Comment by effl-lab** [comment]
좋네요 ㅎㅎㅎ
https://gohugo.io/templates/internal/#google-analytics

**Comment by jaeho-lee** [comment]
effl.postech@gmail.com 계정으로 링크했는데요, 한번 48시간 뒤에 데이터 뜨기 시작하는 것 같으면 close해주세요!

**Comment by jaeho-lee** [comment]
데이터 뜨는 것 확인했습니다. 닫습니다!
